name: pockemon_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  anabebe_packages:
    git:
      url: https://github.com/anabebe1020/anabebe_packages.git
      ref: master
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  graphql: ^5.0.1-beta.5
  artemis: ^7.2.3-beta
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^1.1.0
  connectivity_plus: ^2.2.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/launcher01.png"
  android: true
  ios: true
