name: pockemon_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  google_fonts: ^2.3.1
  graphql: ^5.0.1-beta.5
  artemis: ^7.2.3-beta
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
